notifications:
  email: true

sudo: false

language: python
python:
  - "2.7"
install:
  - pip install -U platformio
  - platformio update
cache:
  - directories: "~/.platformio"

matrix:
  fast_finish: true
  include:

    - name: pio
      script: platformio run -e featheresp32_psychoremote -e nodemcu-woodenboard -e nodemcu-32s_ESPPROTOCOL -e featheresp32_ESPSLAVE -e TTGO_ESPMASTER -e TTGO_ESPMASTER_PADDELEC -e nodemcu-32s_WIFI -e nodemcu-32s_ESPSLAVE -e featheresp32_psycho -e nodemcu-testrun