notifications:
  email: true

sudo: false

language: python
python:
  - "2.7"
install:
  - pip install -U platformio
  - platformio update
cache:
  - directories: "~/.platformio"

matrix:
  fast_finish: true
  include:

    - name: pio
      script: platformio run -e default -e wrover_testrun -e odroidgo -e featheresp32_ESPrelay -e TTGO_IMU_WIFI -e TTGO_PADDELEC -e featheresp32_UDPrelay -e nodemcu -e featheresp32_nunchuk_espnow -e paddelec